### ISSUE TITLE
DataIntegrationModuleProcessingResult - Raw Response not being returned 

### ISSUE THREAD

**Issue by klettg** [digifi-io/digifi-node-js#101]
Followup to #89 since that issue was closed, but in package version ```4.1.4```, there is still an issue. If this is going to be resolved with ```4.1.5```, please feel free to mark this as closed. 

https://github.com/digifi-io/digifi-node-js/blob/0a9aff8bfe75f8dc0b2f40533b060a9e418cc29c/src/api/dp/DecisionProcessingApi.ts#L55-L59

```rawResponse?``` has now been added to the interface, but the *actual* raw response is not being returned anymore. This is actually a breaking change from previous versions, so heads up to anyone else relying on ```rawResponse``` in version ```4.1.4``` 

In previous ```4.x.x``` versions, ```rawResponse``` was *not* on the interface, but was *actually* returned, and now these have swapped.

**Comment by katerina-zaitsava** [comment]
Hi @klettg, we just published new package version `4.1.5` which includes `returnDataSources` parameter. Thank you!
