### ISSUE TITLE
Differing Behavior on ```BorrowersApi``` and ```ApplicationDocumentsDownloadsApi``` 

### ISSUE THREAD

**Issue by klettg** [digifi-io/digifi-node-js#102]
This would probably be categorized as an enhancement, but I wanted to give you an alert that 

```BorrowersApi``` and ```ApplicationDocumentsDownloadsApi``` have different behavior than ```ApplicationsApi``` on ```findById``` (```downloadById``` for ```ApplicationDocumentsDownloadsApi```)

if a non-id is the argument to ```ApplicationsApi.findById('123')``` the error returned is ```ApiRequestError: `id` URL param should be an id.``` with a ```400``` code.

However for ```BorrowersApi``` and ```ApplicationDocumentsDownloadsApi```  the result is just ```Internal Server Error```  and ```500``` codes

**Comment by ilya-tishonok** [comment]
Hi, @klettg , according to description of this issue - this problem is related to DigiFi platform (not SDK problem), cause validation is platform duty. Please, report this issue to DigiFi support.
