### ISSUE TITLE
```BorrowerSearchFields``` email - should this be case-insensitive? 

### ISSUE THREAD

**Issue by klettg** [digifi-io/digifi-node-js#104]
Given that ```AccountsApi.findAccountByEmail``` is case insensitive, I would expect the search param for borrower ```email``` to also be case insensitive, given the close coupling of borrowers <-> accounts

https://github.com/digifi-io/digifi-node-js/blob/a1727e856546077d6adfb1e4bd71d332b12b4a86/src/api/los/BorrowersApi.ts#L62C1-L62C18

**Comment by ilya-tishonok** [comment]
Hi, @klettg , I will report this issue to our support team, cause the issue that you've reported relates to the product API. We will try to fix it on product side as soon as possible.
