### ISSUE TITLE
`ApplicationDocumentsApi.ts` is missing method `delete`

### ISSUE THREAD

**Issue by klettg** [digifi-io/digifi-node-js#112]
https://github.com/digifi-io/digifi-node-js/blob/fdd85b6a24fd3bdc7d091f8a94bf70918a0984e4/src/api/los/ApplicationDocumentsApi.ts#L79

![image](https://github.com/digifi-io/digifi-node-js/assets/32664313/e252c1ac-3ed9-436f-8a0f-11746194fc63)

Npm package description: https://www.npmjs.com/package/@digifi/digifi-node-js?activeTab=readme
![image](https://github.com/digifi-io/digifi-node-js/assets/32664313/a06bd32c-7e87-4398-9e25-88c7f09e4745)

Digifi Developer Documentation: https://docs.digifi.io/reference/delete-application-document

**Comment by ilya-tishonok** [comment]
Hi, @klettg, ```ApplicationDcoumentsApi``` extends ```BasySystemApi``` which has ```delete``` method.
