### ISSUE TITLE
CreateAccount

### ISSUE THREAD

**Issue by SIshaq1839** [digifi-io/digifi-node-js#78]
when trying to create account i get this error
only absolute urls are supported
this is how i created apiClient
`const apiClient = new AuthorizedApiClient(
  process.env.DIGIFI_BASE_URL as string,
  process.env.DIGIFI_API_KEY as string
)`

this is how i used created accountApi instance
`const accountApi = new AccountsApi(apiClient, 'borrowers')`
and this is how i used it
`return await accountApi.createAccount({ borrowerId, password, phone, email })`

**Comment by SIshaq1839** [comment]
```
export async function createAccount(
  borrowerId: string,
  password: string,
  phone: string,
  email: string
) {
  return await accountApi.createAccount(
    { borrowerId, password, phone, email },
    3600
  )
}
```
i am getting 404 not found. Need help, This is the only endpoint that is not working. I am using sandbox env
This is the base url **https://cloud.digifi.io/v2/los/api** its working for borrowers and application endpoints.

**Comment by ilya-tishonok** [comment]
Hi, @SIshaq1839 , I will close an issues, cause it seems like the issue that you've described doesn't relate to ```digifi-node-js``` library.
