### ISSUE TITLE
ExternalIntegrationProcessingResult mismatch with actual API endpoint response

### ISSUE THREAD

**Issue by klettg** [digifi-io/digifi-node-js#86]
https://github.com/digifi-io/digifi-node-js/blame/173273b4dfb6bb78eca10940273f7ed8ae9b2a55/src/api/los/ApplicationIntegrationProcessingApi.ts#L10

![image](https://github.com/digifi-io/digifi-node-js/assets/32664313/1d96e7e3-ae9a-4390-b2a8-07e2e639b927)

1. `resultId` is included in response, `id` is not. 
2. `statusCode` is included in response, `status` is not
3. `applicationDisplayId` is included in response, not in interface
4. I do not see an option to return the raw response, even though the interface indicates this is possible with `raw`. I would like to extract the raw response.

```
{ //Actual
  resultId: string,
  applicationDisplayId: string,
  statusCode: number,
  ...
  integrationId: string,
  integrationName: string,
  outputs: Record<string, VariableValue>;
  result: ExternalIntegrationResultType;
  applicationId?: string;
  applicationName?: string;
}
```

**Comment by klettg** [comment]
@ilya-tishonok I see you changed ```raw?``` to ```rawResponse?``` but I don't think ```rawResponse?``` is correctly being returned either, I don't think that will resolve the missing raw response

**Comment by ilya-tishonok** [comment]
@klettg , ```rawResponse``` is correct one. I've created a new PR which will allow to return raw response in response.

**Comment by klettg** [comment]
thanks! @ilya-tishonok  will this be in next release (assuming 4.1.5)?
